version: '3.8'

services:
  server_green:
    build: ./weather-server
    ports:
      - '3001:3000'
    environment: 
      - NODE_ENV=prod
    volumes:
      - /home/ec2-user/regional-weather:/app/weather-server 
    depends_on:
      - redis
    networks:
      - app_network

networks:
  app_network: 

