version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  server_blue:
    build: ./weather-server
    ports:
      - '3002:3000'
    environment: 
      - NODE_ENV=prod
    volumes:
      - /home/ec2-user/regional-weather:/app/weather-server 
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    environment:
      - ACTIVE_SERVER=server_blue:3002
    volumes:
      - ./weather-server/nginx/nginx_blue.conf:/etc/nginx/nginx.conf
    ports:
      - "3000:2000"
    depends_on:
      - server_blue

volumes:
  redis-data:
