version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  server_green:
    build: ./weather-server
    ports:
      - '3001:3000'
    environment: 
      - NODE_ENV=prod
    volumes:
      - /home/ec2-user/regional-weather:/app/weather-server 
    depends_on:
      - redis

  server_blue:
    build: ./weather-server
    ports:
      - '3002:3000'
    environment: 
      - NODE_ENV=prod
    volumes:
      - /home/ec2-user/regional-weather:/app/weather-server 
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    volumes:
      - ./weather-server/nginx/templates:/etc/nginx/templates
    ports:
      - "3000:2000"
    environment:
      - ACTIVE_SERVER=server_green:3001  # 초기 활성 서버
    command: /bin/sh -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
    depends_on:
      - server_green
      - server_blue

volumes:
  redis-data:
