version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_container
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3000:2000"
      - "2000:2001"
    networks:
      - app_network

networks:
  app_network: 
