version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx_container
    volumes:
      - ./weather-server/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3000:2000"
    networks:
      - app_network

volumes:
  redis-data:

networks:
  app_network: 
