version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  weather:
    build: ./
    ports:
      - '3000:3000'
    volumes:
      - aws-directory:/app/weather-server 
    depends_on:
      - redis

volumes:
  redis-data:
